{% set version = "2.2.1" %}

package:
  name: gocryptfs
  version: {{ version }}
source:
  git_rev: v{{ version }}
  git_url: https://github.com/rfjakob/gocryptfs
build:
  script:
    - bash build-without-openssl.bash
  script_env:
    - GOPATH={{ PREFIX }}
    {% if target_platform == 'linux-64' %}
    - GOARCH=arm64
    {% endif %}
    {% if target_platform == 'linux-aarch64' %}
    - GOARCH=arm64
    {% endif %}

requirements:
  build:
    - go
    - pkg-config
    - {{ compiler('c') }}
