package:
  name: bindfs
  version: 1.15.1
source:
  git_rev: 1.15.1
  git_url: https://github.com/mpartel/bindfs

requirements:
  build:
    - automake
    - pkg-config
    - libtool
    - libfuse
    - {{ compiler('c') }}
