{% set version = "1.15.1" %}

package:
  name: bindfs
  version: {{ version }}
source:
  git_rev: {{ version }}
  git_url: https://github.com/mpartel/bindfs

requirements:
  build:
    - automake
    - pkg-config
    - libtool
    - {{ compiler('c') }}
  host:
    - libfuse
  run:
    - libfuse
