name: 'Conda Upload'
description: 'Publish conda package on Linux'
inputs:
  anaconda-token:
    description: 'Anaconda token for uploading the package'
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniforge-version: latest
    - name: Install dependency
      shell: bash -l {0}
      run: |
        conda install anaconda-client
    - uses: actions/download-artifact@v3
      with:
        name: artifact
        path: ./
    - name: Publish to Anaconda
      shell: bash -l {0}
      run: |
        anaconda --token "${{ inputs.anaconda-token }}" upload --force ./*.tar.bz2
