name: 'Conda Build'
description: 'Build and publish conda package on Linux'
inputs:
  anaconda-token:
    description: 'Anaconda token for uploading the package'
    required: false
    default: null
  recipe-dir:
    description: 'Directory to the conda recipe'
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniforge-version: latest
    - name: Build Package
      shell: bash -l {0}
      id: build
      run: |
        conda build "${{ inputs.recipe-dir }}" -c sshockwave
    - name: Publish to Anaconda
      shell: bash -l {0}
      if: inputs.anaconda-token
      run: |
        conda install anaconda-client
        anaconda --token "${{ inputs.anaconda-token }}" upload --force "$CONDA_PREFIX"/conda-bld/*/*.tar.bz2
