{% set version = "0.6.1" %}

package:
  name: libjxl
  version: {{ version }}
build:
  number: 0
  script_env:
   - JXL_VER=v{{ version }}
requirements:
  build:
    - pkg-config
    - cmake
    - clangxx
  host:
    - libbrotlienc
    - gflags
    # optional image codec libraries
    - giflib
    - libjpeg-turbo
    - openexr
    - libpng
    - libwebp
  run:
