{% set version = "0.12.0" %}

package:
  name: lux
  version: {{ version }}
build:
  script:
    - {{ 'go install github.com/iawia002/lux@v' + version }}
  script_env:
    - {{ 'GOPATH=' + PREFIX }}

requirements:
  build:
    - go
    - {{ compiler('c') }}
  run:
    - ffmpeg
