{% set version = "0.12.0" %}

package:
  name: lux
  version: {{ version }}
build:
  script:
    - go install github.com/iawia002/lux@v{{ version }}
  script_env:
    - GOPATH={{ PREFIX }}
    {% if target_platform == 'linux-64' %}
    - GOARCH=arm64
    {% endif %}
    {% if target_platform == 'linux-aarch64' %}
    - GOARCH=arm64
    {% endif %}

requirements:
  build:
    - go
    - {{ compiler('c') }}
  run:
    - ffmpeg
