name: bindfs
on:
  push:
    paths:
      - recipe/bindfs/**
  pull_request:
    paths:
      - recipe/bindfs/**
  workflow_dispatch:
jobs:
  conda:
    uses: ./.github/workflows/reuse-conda.yml
    with:
      recipe_name: bindfs
    secrets:
      anaconda_token: ${{ github.event_name != 'pull_request' && secrets.ANACONDA_TOKEN || '' }}
