name: bindfs
on:
  push:
    paths:
      - conda/bindfs/**
  pull_request:
    paths:
      - conda/bindfs/**
  workflow_dispatch:
jobs:
  conda:
    uses: ./.github/workflows/reuse-conda.yml
    with:
      recipe_name: bindfs
    secrets:
      anaconda_token: ${{ secrets.ANACONDA_TOKEN }}
