name: zimg
on:
  push:
    paths:
      - conda/zimg/**
  pull_request:
    paths:
      - conda/zimg/**
  workflow_dispatch:
jobs:
  conda:
    uses: ./.github/workflows/reuse-conda.yml
    with:
      recipe_name: zimg
      do_deploy: ${{ github.event_name != 'pull_request' }}
    secrets:
      anaconda_token: ${{ secrets.ANACONDA_TOKEN }}
