name: Scheduler
on:
  schedule:
    - cron: '0 */6 * * *' # Every day
jobs:
  update-syosetu:
    name: Syosetu
    uses: ./.github/workflows/radar-syosetu.yml
    secrets: inherit
  update-arknights:
    name: Arknights
    uses: ./.github/workflows/radar-arknights.yml
    secrets: inherit
  update-pixiv:
    name: Pixiv
    uses: ./.github/workflows/radar-pixiv.yml
    secrets: inherit
  update-torrent:
    name: Torrent
    uses: ./.github/workflows/radar-torrent.yml
    secrets: inherit
